//
// File generated by rootcint at Sun Mar 10 20:30:53 2019

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME PHSartreGenTrigger_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "PHSartreGenTrigger_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void PHSartreGenTrigger_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void PHSartreGenTrigger_Dictionary();
   static void delete_PHSartreGenTrigger(void *p);
   static void deleteArray_PHSartreGenTrigger(void *p);
   static void destruct_PHSartreGenTrigger(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::PHSartreGenTrigger*)
   {
      ::PHSartreGenTrigger *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::PHSartreGenTrigger),0);
      static ::ROOT::TGenericClassInfo 
         instance("PHSartreGenTrigger", "./PHSartreGenTrigger.h", 12,
                  typeid(::PHSartreGenTrigger), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &PHSartreGenTrigger_Dictionary, isa_proxy, 3,
                  sizeof(::PHSartreGenTrigger) );
      instance.SetDelete(&delete_PHSartreGenTrigger);
      instance.SetDeleteArray(&deleteArray_PHSartreGenTrigger);
      instance.SetDestructor(&destruct_PHSartreGenTrigger);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::PHSartreGenTrigger*)
   {
      return GenerateInitInstanceLocal((::PHSartreGenTrigger*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::PHSartreGenTrigger*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void PHSartreGenTrigger_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::PHSartreGenTrigger*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrapper around operator delete
   static void delete_PHSartreGenTrigger(void *p) {
      delete ((::PHSartreGenTrigger*)p);
   }
   static void deleteArray_PHSartreGenTrigger(void *p) {
      delete [] ((::PHSartreGenTrigger*)p);
   }
   static void destruct_PHSartreGenTrigger(void *p) {
      typedef ::PHSartreGenTrigger current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::PHSartreGenTrigger

/********************************************************
* PHSartreGenTrigger_Dict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablePHSartreGenTrigger_Dict();

extern "C" void G__set_cpp_environmentPHSartreGenTrigger_Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("PHSartreGenTrigger.h");
  G__cpp_reset_tagtablePHSartreGenTrigger_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevPHSartreGenTrigger_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* PHSartreGenTrigger */
static int G__PHSartreGenTrigger_Dict_169_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((PHSartreGenTrigger*) G__getstructoffset())->Apply((Event*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHSartreGenTrigger_Dict_169_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         string* pobj;
         string xobj = ((PHSartreGenTrigger*) G__getstructoffset())->GetName();
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHSartreGenTrigger_Dict_169_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<int>* pobj;
         vector<int> xobj = ((PHSartreGenTrigger*) G__getstructoffset())->convertToInts(*((string*) G__int(libp->para[0])));
         pobj = new vector<int>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHSartreGenTrigger_Dict_169_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const PHSartreGenTrigger*) G__getstructoffset())->Verbosity());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHSartreGenTrigger_Dict_169_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHSartreGenTrigger*) G__getstructoffset())->Verbosity((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__PHSartreGenTrigger_Dict_169_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   PHSartreGenTrigger* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new PHSartreGenTrigger(*(PHSartreGenTrigger*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__PHSartreGenTrigger_DictLN_PHSartreGenTrigger));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef PHSartreGenTrigger G__TPHSartreGenTrigger;
static int G__PHSartreGenTrigger_Dict_169_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (PHSartreGenTrigger*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((PHSartreGenTrigger*) (soff+(sizeof(PHSartreGenTrigger)*i)))->~G__TPHSartreGenTrigger();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (PHSartreGenTrigger*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((PHSartreGenTrigger*) (soff))->~G__TPHSartreGenTrigger();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__PHSartreGenTrigger_Dict_169_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   PHSartreGenTrigger* dest = (PHSartreGenTrigger*) G__getstructoffset();
   *dest = *(PHSartreGenTrigger*) libp->para[0].ref;
   const PHSartreGenTrigger& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* PHSartreGenTrigger */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncPHSartreGenTrigger_Dict {
 public:
  G__Sizep2memfuncPHSartreGenTrigger_Dict(): p(&G__Sizep2memfuncPHSartreGenTrigger_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncPHSartreGenTrigger_Dict::*p)();
};

size_t G__get_sizep2memfuncPHSartreGenTrigger_Dict()
{
  G__Sizep2memfuncPHSartreGenTrigger_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancePHSartreGenTrigger_Dict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablePHSartreGenTrigger_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__PHSartreGenTrigger_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PHSartreGenTrigger_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHSartreGenTrigger_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PHSartreGenTrigger_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHSartreGenTrigger_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__PHSartreGenTrigger_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PHSartreGenTrigger_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHSartreGenTrigger_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PHSartreGenTrigger_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHSartreGenTrigger_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__PHSartreGenTrigger_DictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PHSartreGenTrigger_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHSartreGenTrigger_DictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PHSartreGenTrigger_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHSartreGenTrigger_DictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* PHSartreGenTrigger */
static void G__setup_memvarPHSartreGenTrigger(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__PHSartreGenTrigger_DictLN_PHSartreGenTrigger));
   { PHSartreGenTrigger *p; p=(PHSartreGenTrigger*)0x1000; if (p) { }
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"m_Verbosity=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__PHSartreGenTrigger_DictLN_string),-1,-1,4,"m_Name=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarPHSartreGenTrigger_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncPHSartreGenTrigger(void) {
   /* PHSartreGenTrigger */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__PHSartreGenTrigger_DictLN_PHSartreGenTrigger));
   G__memfunc_setup("PHSartreGenTrigger",1783,(G__InterfaceMethod) NULL, 105, G__get_linked_tagnum(&G__PHSartreGenTrigger_DictLN_PHSartreGenTrigger), -1, 0, 1, 1, 2, 0, "u 'string' - 11 '\"PHSartreGenTrigger\"' name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Apply",518,G__PHSartreGenTrigger_Dict_169_0_2, 103, -1, -1, 0, 1, 1, 1, 0, "U 'Event' - 0 - event", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetName",673,G__PHSartreGenTrigger_Dict_169_0_3, 117, G__get_linked_tagnum(&G__PHSartreGenTrigger_DictLN_string), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("convertToInts",1378,G__PHSartreGenTrigger_Dict_169_0_4, 117, G__get_linked_tagnum(&G__PHSartreGenTrigger_DictLN_vectorlEintcOallocatorlEintgRsPgR), G__defined_typename("vector<int>"), 0, 1, 1, 1, 0, "u 'string' - 0 - s", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Verbosity",967,G__PHSartreGenTrigger_Dict_169_0_5, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Verbosity",967,G__PHSartreGenTrigger_Dict_169_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - v", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("PHSartreGenTrigger", 1783, G__PHSartreGenTrigger_Dict_169_0_7, (int) ('i'), G__get_linked_tagnum(&G__PHSartreGenTrigger_DictLN_PHSartreGenTrigger), -1, 0, 1, 1, 1, 0, "u 'PHSartreGenTrigger' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~PHSartreGenTrigger", 1909, G__PHSartreGenTrigger_Dict_169_0_8, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__PHSartreGenTrigger_Dict_169_0_9, (int) ('u'), G__get_linked_tagnum(&G__PHSartreGenTrigger_DictLN_PHSartreGenTrigger), -1, 1, 1, 1, 1, 0, "u 'PHSartreGenTrigger' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncPHSartreGenTrigger_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalPHSartreGenTrigger_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcPHSartreGenTrigger_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__PHSartreGenTrigger_DictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__PHSartreGenTrigger_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__PHSartreGenTrigger_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PHSartreGenTrigger_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__PHSartreGenTrigger_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PHSartreGenTrigger_DictLN_Event = { "Event" , 99 , -1 };
G__linked_taginfo G__PHSartreGenTrigger_DictLN_PHSartreGenTrigger = { "PHSartreGenTrigger" , 99 , -1 };
G__linked_taginfo G__PHSartreGenTrigger_DictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__PHSartreGenTrigger_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablePHSartreGenTrigger_Dict() {
  G__PHSartreGenTrigger_DictLN_string.tagnum = -1 ;
  G__PHSartreGenTrigger_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__PHSartreGenTrigger_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PHSartreGenTrigger_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__PHSartreGenTrigger_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PHSartreGenTrigger_DictLN_Event.tagnum = -1 ;
  G__PHSartreGenTrigger_DictLN_PHSartreGenTrigger.tagnum = -1 ;
  G__PHSartreGenTrigger_DictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__PHSartreGenTrigger_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablePHSartreGenTrigger_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__PHSartreGenTrigger_DictLN_string);
   G__get_linked_tagnum_fwd(&G__PHSartreGenTrigger_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__PHSartreGenTrigger_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PHSartreGenTrigger_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__PHSartreGenTrigger_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PHSartreGenTrigger_DictLN_Event);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__PHSartreGenTrigger_DictLN_PHSartreGenTrigger),sizeof(PHSartreGenTrigger),-1,197888,(char*)NULL,G__setup_memvarPHSartreGenTrigger,G__setup_memfuncPHSartreGenTrigger);
   G__get_linked_tagnum_fwd(&G__PHSartreGenTrigger_DictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__PHSartreGenTrigger_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupPHSartreGenTrigger_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupPHSartreGenTrigger_Dict()");
  G__set_cpp_environmentPHSartreGenTrigger_Dict();
  G__cpp_setup_tagtablePHSartreGenTrigger_Dict();

  G__cpp_setup_inheritancePHSartreGenTrigger_Dict();

  G__cpp_setup_typetablePHSartreGenTrigger_Dict();

  G__cpp_setup_memvarPHSartreGenTrigger_Dict();

  G__cpp_setup_memfuncPHSartreGenTrigger_Dict();
  G__cpp_setup_globalPHSartreGenTrigger_Dict();
  G__cpp_setup_funcPHSartreGenTrigger_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncPHSartreGenTrigger_Dict();
  return;
}
class G__cpp_setup_initPHSartreGenTrigger_Dict {
  public:
    G__cpp_setup_initPHSartreGenTrigger_Dict() { G__add_setup_func("PHSartreGenTrigger_Dict",(G__incsetup)(&G__cpp_setupPHSartreGenTrigger_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initPHSartreGenTrigger_Dict() { G__remove_setup_func("PHSartreGenTrigger_Dict"); }
};
G__cpp_setup_initPHSartreGenTrigger_Dict G__cpp_setup_initializerPHSartreGenTrigger_Dict;

