/********************************************************************
* PHSartreParticleTrigger_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error PHSartreParticleTrigger_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablePHSartreParticleTrigger_Dict();
extern void G__cpp_setup_inheritancePHSartreParticleTrigger_Dict();
extern void G__cpp_setup_typetablePHSartreParticleTrigger_Dict();
extern void G__cpp_setup_memvarPHSartreParticleTrigger_Dict();
extern void G__cpp_setup_globalPHSartreParticleTrigger_Dict();
extern void G__cpp_setup_memfuncPHSartreParticleTrigger_Dict();
extern void G__cpp_setup_funcPHSartreParticleTrigger_Dict();
extern void G__set_cpp_environmentPHSartreParticleTrigger_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "PHSartreParticleTrigger.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PHSartreParticleTrigger_DictLN_string;
extern G__linked_taginfo G__PHSartreParticleTrigger_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__PHSartreParticleTrigger_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PHSartreParticleTrigger_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__PHSartreParticleTrigger_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PHSartreParticleTrigger_DictLN_Event;
extern G__linked_taginfo G__PHSartreParticleTrigger_DictLN_PHSartreGenTrigger;
extern G__linked_taginfo G__PHSartreParticleTrigger_DictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__PHSartreParticleTrigger_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PHSartreParticleTrigger_DictLN_PHSartreParticleTrigger;

/* STUB derived class for protected member access */
