/********************************************************************
* PHSartreGenTrigger_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error PHSartreGenTrigger_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablePHSartreGenTrigger_Dict();
extern void G__cpp_setup_inheritancePHSartreGenTrigger_Dict();
extern void G__cpp_setup_typetablePHSartreGenTrigger_Dict();
extern void G__cpp_setup_memvarPHSartreGenTrigger_Dict();
extern void G__cpp_setup_globalPHSartreGenTrigger_Dict();
extern void G__cpp_setup_memfuncPHSartreGenTrigger_Dict();
extern void G__cpp_setup_funcPHSartreGenTrigger_Dict();
extern void G__set_cpp_environmentPHSartreGenTrigger_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "PHSartreGenTrigger.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PHSartreGenTrigger_DictLN_string;
extern G__linked_taginfo G__PHSartreGenTrigger_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__PHSartreGenTrigger_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PHSartreGenTrigger_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__PHSartreGenTrigger_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PHSartreGenTrigger_DictLN_Event;
extern G__linked_taginfo G__PHSartreGenTrigger_DictLN_PHSartreGenTrigger;
extern G__linked_taginfo G__PHSartreGenTrigger_DictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__PHSartreGenTrigger_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
