/********************************************************************
* PHSartre_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error PHSartre_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablePHSartre_Dict();
extern void G__cpp_setup_inheritancePHSartre_Dict();
extern void G__cpp_setup_typetablePHSartre_Dict();
extern void G__cpp_setup_memvarPHSartre_Dict();
extern void G__cpp_setup_globalPHSartre_Dict();
extern void G__cpp_setup_memfuncPHSartre_Dict();
extern void G__cpp_setup_funcPHSartre_Dict();
extern void G__set_cpp_environmentPHSartre_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "PHSartre.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PHSartre_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__PHSartre_DictLN_string;
extern G__linked_taginfo G__PHSartre_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__PHSartre_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PHSartre_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__PHSartre_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PHSartre_DictLN_Fun4AllBase;
extern G__linked_taginfo G__PHSartre_DictLN_PHCompositeNode;
extern G__linked_taginfo G__PHSartre_DictLN_SubsysReco;
extern G__linked_taginfo G__PHSartre_DictLN_PHHepMCGenHelper;
extern G__linked_taginfo G__PHSartre_DictLN_PHHepMCGenHelpercLcLVTXFUNC;
extern G__linked_taginfo G__PHSartre_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__PHSartre_DictLN_TFile;
extern G__linked_taginfo G__PHSartre_DictLN_TTree;
extern G__linked_taginfo G__PHSartre_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__PHSartre_DictLN_Sartre;
extern G__linked_taginfo G__PHSartre_DictLN_Event;
extern G__linked_taginfo G__PHSartre_DictLN_EventGeneratorSettings;
extern G__linked_taginfo G__PHSartre_DictLN_PHSartreGenTrigger;
extern G__linked_taginfo G__PHSartre_DictLN_TGenPhaseSpace;
extern G__linked_taginfo G__PHSartre_DictLN_PHSartre;
extern G__linked_taginfo G__PHSartre_DictLN_vectorlEPHSartreGenTriggermUcOallocatorlEPHSartreGenTriggermUgRsPgR;
extern G__linked_taginfo G__PHSartre_DictLN_reverse_iteratorlEvectorlEPHSartreGenTriggermUcOallocatorlEPHSartreGenTriggermUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PHSartre_DictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__PHSartre_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PHSartre_DictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__PHSartre_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
